### ISSUE TITLE
Not text out put in text file

### ISSUE THREAD

**Issue by diomededavid** [hemanth/gulp-html2txt#34]
I am running gulp watch, the precess runs fine, but the ext file does not output any text within the file. I just realized that when I add the options is when the text file does not display. Its not clear to me how I add the options to the gulp file.

Here is my current code for the html2txt task.

`// html2txt Task
gulp.task('html2txt', function(){
gulp.src('index.html')
 .pipe(html2txt())
 .pipe(gulp.dest('dist'));
});`

**Comment by hemanth** [comment]
solved?
